version: '3.3'
services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    env_file:
      - ./django/.env
    ports:
      - '8000:8000'
    volumes:
      - ./django:/code
    command: 'python /code/manage.py runserver 0.0.0.0:8000'

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    env_file:
      - ./jupyter/.env
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/notebooks
    command: 'jupyter notebook --ip=0.0.0.0 --port=8888 --NotebookApp.notebook_dir=/notebooks --allow-root'